name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download codes
        uses: actions/checkout@v6

      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: install node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: pnpm

      - name: Build
        run: |
          pnpm install
          pnpm build # npm run build / pnpm build
          touch ./dist/.nojekyll

      - name: configure github pages
        uses: actions/configure-pages@v6

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
